spring.application.name=SchoolFoodSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/SchoolFoodSystem
spring.datasource.username=postgres
spring.datasource.password=123456


spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true


logging.level.org.flywaydb=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html