CREATE TABLE autorizate (
    user_id VARCHAR(255) NOT NULL PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    rule VARCHAR(255) NOT NULL
);

CREATE TABLE order (
    order_id VARCHAR(255) NOT NULL PRIMARY KEY,
    dish_id VARCHAR(255) NOT NULL PRIMARY KEY,
    dish_name VARCHAR(255) NOT NULL,
    caloric_value VARCHAR(255) NOT NULL,
    price VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL
);

CREATE TABLE order_history (
    order_id VARCHAR(255) NOT NULL PRIMARY KEY,
    dish_id VARCHAR(255) NOT NULL PRIMARY KEY,
    dish_name VARCHAR(255) NOT NULL,
    caloric_value VARCHAR(255) NOT NULL,
    price VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL
);

CREATE TABLE menu (
     dish_id VARCHAR(255) NOT NULL PRIMARY KEY,
     dish_name VARCHAR(255) NOT NULL
);

ALTER TABLE order
ADD CONSTRAINT fk_dish_id FOREIGN KEY (dish_id) REFERENCES menu(dish_id) ON DELETE CASCADE;